/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import rx.Observable;

import java.util.concurrent.TimeUnit;

public class LibraryTest {

    @Test
    public void name() throws Exception {
//
//        Integer value = Single.fromCallable( () -> {
//            Thread.sleep( 2000 );
//            return 1;
//        } ).timeout( 1, TimeUnit.SECONDS );


        Observable<Long> timer = Observable.timer( 1000, TimeUnit.MILLISECONDS );


//        timer.toBlocking().subscribe( longy -> {
//            return Single.just(123);
//        } );

//        timer
//                .fromCallable( () -> {
//                    System.out.println("peas!!!");
//                    return 123;
//                } ).subscribe( integer -> {
//                    System.out.println("here");
//                } );

//        Integer value = integerSingle.toBlocking().value();
//
//        assertThat(value, is(123));
//        assertThat(value, is(1));
        Thread.sleep( 2000 );
    }


}
